import Navbar from '@/components/Navbar/Navbar'
import '../src/styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='es'>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
